default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 'localhost'
  port: 5432

development:
  <<: *default
  database: coaxsoft_test_project_development